### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by EvaSDK** [Polyconseil/devpi-metawheel#3]
Metadata of the package does not agree on its license as can be seen on pypi:
https://pypi.python.org/pypi/devpi-metawheel
https://github.com/Polyconseil/devpi-metawheel/blob/master/setup.py#L11
https://github.com/Polyconseil/devpi-metawheel/blob/master/setup.py#L27
https://github.com/Polyconseil/devpi-metawheel/blob/master/LICENSE

**Comment by xavfernandez** [comment]
Indeed ^^
License should now be the same everywhere with https://github.com/Polyconseil/devpi-metawheel/commit/2ba2f5cae2e9626e3eee4cdc191cb2c3f5f79871

Thanks
